--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://localhost:3000/api/v1/tasks?
    body: task[name]=My%20First%20Task&task[named_price]=20&task[city_id]=4
    headers: 
      x-client-application: 
      - euqmQpzV04GmN1dJTY639PdI7eiSjCjI3lKTkPWn
      authorization: 
      - OAuth cNPyB6KypcdDjFb8KhQ7EOZzBpwcenMMvnQBbSHM
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 200
      message: OK
    headers: 
      etag: 
      - "\"d9f969ea55158e20892d6cbd799e9932\""
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "2762"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2010-04-19)
      date: 
      - Mon, 31 Oct 2011 05:05:54 GMT
      content-length: 
      - "613"
      cache-control: 
      - private, max-age=0, must-revalidate
    body: "{\"name\":\"My First Task\",\"city\":{\"name\":\"New York City\",\"lng\":-74.005973,\"id\":4,\"links\":{\"get\":\"/api/v1/cities/4\"},\"lat\":40.714353},\"named_price\":20,\"complete_by_time\":1320087600,\"id\":22561,\"state_changed_at\":1320037553,\"cost_in_cents\":0,\"links\":{\"html\":\"http://local.taskrabbit.com/tasks/my-first-task--15\",\"get\":\"/api/v1/tasks/22561\",\"delete\":\"/api/v1/tasks/22561\",\"put\":\"/api/v1/tasks/22561\",\"authenticated\":\"http://local.taskrabbit.com/go/0261e1dc7ead0880c1cbf8f936f5767935ac2fc2a95ab080aa54906fff69652fbf142125644068068c6fb2655124f8b92249\"},\"state_label\":\"posted\",\"assign_by_time\":1320073200,\"state\":\"opened\"}"
    http_version: "1.1"
