--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://localhost:3000/api/v1/tasks?
    body: task[name]=My%20First%20Task&task[named_price]=20&task[city_id]=4
    headers: 
      x-client-application: 
      - euqmQpzV04GmN1dJTY639PdI7eiSjCjI3lKTkPWn
      authorization: 
      - OAuth RhyRtRg1bRNyqmdozkY6JJJ3eGDpoRGTm9AXUudp
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 200
      message: OK
    headers: 
      etag: 
      - "\"8a95a07c86d343046460095bc788cb54\""
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "3015"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2010-04-19)
      date: 
      - Wed, 02 Nov 2011 02:36:07 GMT
      content-length: 
      - "613"
      cache-control: 
      - private, max-age=0, must-revalidate
    body: "{\"name\":\"My First Task\",\"city\":{\"name\":\"New York City\",\"lng\":-74.005973,\"id\":4,\"links\":{\"get\":\"/api/v1/cities/4\"},\"lat\":40.714353},\"named_price\":20,\"complete_by_time\":1320260400,\"id\":22564,\"state_changed_at\":1320201366,\"cost_in_cents\":0,\"links\":{\"html\":\"http://local.taskrabbit.com/tasks/my-first-task--17\",\"get\":\"/api/v1/tasks/22564\",\"delete\":\"/api/v1/tasks/22564\",\"put\":\"/api/v1/tasks/22564\",\"authenticated\":\"http://local.taskrabbit.com/go/832a30e0e13c600552ec2ef734fe7ad604a778e21479a3b5e7e288e852b1e978689c9c0d0bc20a8f55d667af634ed4f0ba14\"},\"state_label\":\"posted\",\"assign_by_time\":1320246000,\"state\":\"opened\"}"
    http_version: "1.1"
