--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://localhost:3000/api/v1/tasks?
    body: task[name]=My%20First%20Task&task[named_price]=20&task[city_id]=4
    headers: 
      x-client-application: 
      - euqmQpzV04GmN1dJTY639PdI7eiSjCjI3lKTkPWn
      authorization: 
      - OAuth RhyRtRg1bRNyqmdozkY6JJJ3eGDpoRGTm9AXUudp
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 422
      message: 
    headers: 
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "718"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2011-02-18)
      date: 
      - Sat, 17 Mar 2012 23:13:17 GMT
      content-length: 
      - "341"
      cache-control: 
      - no-cache
    body: "{\"errors\":{\"messages\":[\"Whoa! You're posting Tasks too quickly. Our TaskRabbits need a break. Please try again later.\"],\"fields\":[[\"base\",\"Whoa! You're posting Tasks too quickly. Our TaskRabbits need a break. Please try again later.\"]]},\"error\":\"Whoa! You're posting Tasks too quickly. Our TaskRabbits need a break. Please try again later.\"}"
    http_version: "1.1"
