--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://localhost:3000/api/v1/tasks?
    body: 
    headers: 
      oauth: 
      - ""
      x-client-application: 
      - euqmQpzV04GmN1dJTY639PdI7eiSjCjI3lKTkPWn
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 401
      message: Unauthorized
    headers: 
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "88"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2010-04-19)
      date: 
      - Sun, 30 Oct 2011 22:57:16 GMT
      content-length: 
      - "63"
      cache-control: 
      - no-cache
    body: "{\"error\":\"There must be an authenticated user for this action\"}"
    http_version: "1.1"
