--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://localhost:3000/api/v1/tasks?
    body: task[name]=My%20First%20Task&task[named_price]=20&task[city_id]=4
    headers: 
      x-client-application: 
      - euqmQpzV04GmN1dJTY639PdI7eiSjCjI3lKTkPWn
      authorization: 
      - OAuth sjCuNHsxMRkFiJGpLWZzYJksDjfnXtDvDcPuuDkn
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 201
      message: Created
    headers: 
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "2643"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2010-04-19)
      date: 
      - Mon, 31 Oct 2011 05:05:50 GMT
      content-length: 
      - "693"
      cache-control: 
      - no-cache
    body: "{\"name\":\"My First Task\",\"city\":{\"name\":\"New York City\",\"lng\":-74.005973,\"id\":4,\"links\":{\"get\":\"/api/v1/cities/4\"},\"lat\":40.714353},\"named_price\":20,\"complete_by_time\":1320087600,\"id\":22560,\"state_changed_at\":1320037548,\"cost_in_cents\":0,\"links\":{\"html\":\"http://local.taskrabbit.com/tasks/my-first-task--14\",\"get\":\"/api/v1/tasks/22560\",\"delete\":\"/api/v1/tasks/22560\",\"put\":\"/api/v1/tasks/22560\",\"authenticated\":\"http://local.taskrabbit.com/go/b991d2f9080f6394914d111e4efda930d3655f81321a2b00aac66c33cd2b2e6ad0e185aae4c8985088de7d30027663c62df2\",\"redirect\":\"https://local.taskrabbit.com/tasks/my-first-task--14?card=true\"},\"state_label\":\"not posted\",\"assign_by_time\":1320073200,\"state\":\"unpaid\"}"
    http_version: "1.1"
