--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://localhost:3000/api/v1/tasks?
    body: task[name]=My%20First%20Task&task[named_price]=20&task[city_id]=4&task[other_locations_attributes][][city]=Boston&task[other_locations_attributes][][address]=123%20Main%20St&task[other_locations_attributes][][name]=Home&task[other_locations_attributes][][zip]=02154&task[other_locations_attributes][][lng]=-71.059774&task[other_locations_attributes][][lat]=42.358432&task[other_locations_attributes][][state]=MA&task[other_locations_attributes][][name]=Middle%20of%20the%20park&task[other_locations_attributes][][lng]=-71.059772&task[other_locations_attributes][][lat]=42.358430
    headers: 
      x-client-application: 
      - euqmQpzV04GmN1dJTY639PdI7eiSjCjI3lKTkPWn
      authorization: 
      - OAuth RhyRtRg1bRNyqmdozkY6JJJ3eGDpoRGTm9AXUudp
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 200
      message: OK
    headers: 
      etag: 
      - "\"10cd4f905b5cad3e2564d16f6d4d0942\""
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "9675"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2010-04-19)
      date: 
      - Wed, 09 Nov 2011 01:26:12 GMT
      content-length: 
      - "1010"
      cache-control: 
      - private, max-age=0, must-revalidate
    body: "{\"name\":\"My First Task\",\"city\":{\"name\":\"New York City\",\"lng\":-74.005973,\"id\":4,\"links\":{\"get\":\"/api/v1/cities/4\"},\"lat\":40.714353},\"named_price\":20,\"complete_by_time\":1320868800,\"id\":22585,\"state_changed_at\":1320801971,\"cost_in_cents\":0,\"links\":{\"html\":\"http://local.taskrabbit.com/tasks/my-first-task--38\",\"get\":\"/api/v1/tasks/22585\",\"delete\":\"/api/v1/tasks/22585\",\"put\":\"/api/v1/tasks/22585\",\"authenticated\":\"http://local.taskrabbit.com/go/4aa57a3648f4d246e40d97bd003fed77045007a1d09aff4541afe695552affb6f8c3421462c3101c854e1e9e144e58685d11\"},\"state_label\":\"posted\",\"assign_by_time\":1320854400,\"location_visits\":{\"items\":[{\"address\":\"123 Main St\",\"approximate_radius\":0,\"city\":\"Boston\",\"name\":\"Home\",\"zip\":\"02154\",\"partial\":\"Main St, Boston, MA 02154\",\"lng\":-71.059774,\"id\":17686,\"complete\":\"123 Main St, Boston, MA 02154\",\"location_id\":37448,\"lat\":42.358432,\"state\":\"MA\"},{\"approximate_radius\":0,\"name\":\"Middle of the park\",\"lng\":-71.059772,\"id\":17687,\"location_id\":37449,\"lat\":42.35843}]},\"state\":\"opened\"}"
    http_version: "1.1"
