--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://localhost:3000/api/v1/tasks?
    body: task[name]=My%20First%20Task&task[named_price]=20&task[city_id]=4
    headers: 
      x-client-application: 
      - euqmQpzV04GmN1dJTY639PdI7eiSjCjI3lKTkPWn
      authorization: 
      - OAuth cNPyB6KypcdDjFb8KhQ7EOZzBpwcenMMvnQBbSHM
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 200
      message: OK
    headers: 
      etag: 
      - "\"50964bfb7611739f90813907c251242f\""
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "3800"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2010-04-19)
      date: 
      - Mon, 31 Oct 2011 02:46:50 GMT
      content-length: 
      - "612"
      cache-control: 
      - private, max-age=0, must-revalidate
    body: "{\"name\":\"My First Task\",\"city\":{\"name\":\"New York City\",\"lng\":-74.005973,\"id\":4,\"links\":{\"get\":\"/api/v1/cities/4\"},\"lat\":40.714353},\"named_price\":20,\"complete_by_time\":1320087600,\"id\":22549,\"state_changed_at\":1320029209,\"cost_in_cents\":0,\"links\":{\"html\":\"http://local.taskrabbit.com/tasks/my-first-task--3\",\"get\":\"/api/v1/tasks/22549\",\"delete\":\"/api/v1/tasks/22549\",\"put\":\"/api/v1/tasks/22549\",\"authenticated\":\"http://local.taskrabbit.com/go/a8c54394b14a3bd493fb73dd4fdf93da99421faf864ff9db32279584b58d603775d9fad96a236b34a736adbd3da524a513b0\"},\"state_label\":\"posted\",\"assign_by_time\":1320073200,\"state\":\"opened\"}"
    http_version: "1.1"
