---
- !ruby/struct:VCR::HTTPInteraction
  request: !ruby/struct:VCR::Request
    method: :post
    uri: https://taskrabbitdev.com:443/api/v1/tasks?
    body: task[description]=&task[private_description]=&task[private_runner]=false&task[virtual]=false&task[name]=My%20First%20Task&task[named_price]=20&task[city_id]=4
    headers:
      x-client-application:
      - <API_SECRET>
      authorization:
      - OAuth <USER_WITH_CARD>
  response: !ruby/struct:VCR::Response
    status: !ruby/struct:VCR::ResponseStatus
      code: 200
      message: OK
    headers:
      server:
      - nginx/1.0.11
      date:
      - Fri, 12 Oct 2012 06:50:51 GMT
      content-type:
      - application/json; charset=utf-8
      status:
      - 200 OK
      etag:
      - ! '"9e056879e573f4e359fab517bb401b3c"'
      cache-control:
      - max-age=0, private, must-revalidate
      set-cookie:
      - current_geo=1053; path=/; expires=Wed, 12-Dec-2012 07:50:50 GMT; secure
      x-runtime:
      - '0.446353'
      x-ua-compatible:
      - IE=Edge,chrome=1
      strict-transport-security:
      - max-age=31536000
      content-length:
      - '1038'
    body: ! '{"charge_price":20,"id":142,"named_price":20,"runners":{"items":[]},"cost_in_cents":0,"assign_by_time":1350151200,"assignment_type":"auto","description_properties":[{"value":"","title":"Description","key":"description"},{"value":"","title":"Private
      description","key":"private_description"},{"value":1350151200,"title":"If unassigned,
      Task will expire on","key":"assign_by_time"},{"value":1350237600,"title":"Task
      should be completed by","key":"complete_by_time"}],"state_label":"posted","city":{"id":1053,"lng":-122.419416,"lat":37.77493,"name":"SF
      Bay Area","links":{"get":"/api/v1/cities/3"}},"state_changed_at":1350024650,"name":"My
      First Task","state":"opened","private_runner":false,"complete_by_time":1350237600,"runner_fee":0,"links":{"put":"/api/v1/tasks/142","html":"http://s-app1.taskrabbit.com/tasks/my-first-task--16","get":"/api/v1/tasks/142","authenticated":"http://s-app1.taskrabbit.com/go/0cac931143e6c5d187b614558664b7b57989847b9d14658861928639edb4ce4f63687d762e68b12a8f51272dbfe47c5f0bc3","delete":"/api/v1/tasks/142"}}'
    http_version: '1.1'
- !ruby/struct:VCR::HTTPInteraction
  request: !ruby/struct:VCR::Request
    method: :get
    uri: https://taskrabbitdev.com:443/api/v1/tasks/142?include[task][]=errors&include[task][]=links&include[task][]=error&include[task][]=id&include[task][]=name&include[task][]=user&include[task][]=runner&include[task][]=runners&include[task][]=named_price&include[task][]=charge_price&include[task][]=cost_in_cents&include[task][]=number_runners_to_fill&include[task][]=state_label&include[task][]=city_id&include[task][]=city&include[task][]=description&include[task][]=private_description&include[task][]=private_runner&include[task][]=virtual&include[task][]=state&include[task][]=assignment_type&include[task][]=complete_by_time&include[task][]=state_changed_at&include[task][]=assign_by_time&include[task][]=location_visits&include[task][]=offers&include[task][]=other_locations_attributes&include[task][]=uploaded_photos_attributes&include[task][]=uploaded_sounds_attributes
    body: 
    headers:
      x-client-application:
      - <API_SECRET>
      authorization:
      - OAuth <USER_WITH_CARD>
  response: !ruby/struct:VCR::Response
    status: !ruby/struct:VCR::ResponseStatus
      code: 200
      message: OK
    headers:
      server:
      - nginx/1.0.11
      date:
      - Fri, 12 Oct 2012 06:50:51 GMT
      content-type:
      - application/json; charset=utf-8
      status:
      - 200 OK
      etag:
      - ! '"42735da7ee4768cc1b0b3d64b3eb8fe5"'
      cache-control:
      - max-age=0, private, must-revalidate
      set-cookie:
      - current_geo=1053; path=/; expires=Wed, 12-Dec-2012 07:50:51 GMT; secure
      x-runtime:
      - '0.158178'
      x-ua-compatible:
      - IE=Edge,chrome=1
      strict-transport-security:
      - max-age=31536000
      content-length:
      - '728'
    body: ! '{"charge_price":20,"id":142,"named_price":20,"location_visits":{"items":[]},"runners":{"items":[]},"cost_in_cents":0,"assign_by_time":1350151200,"assignment_type":"auto","state_label":"posted","city":{"id":1053,"lng":-122.419416,"lat":37.77493,"name":"SF
      Bay Area","links":{"get":"/api/v1/cities/3"}},"state_changed_at":1350024650,"name":"My
      First Task","state":"opened","private_runner":false,"complete_by_time":1350237600,"links":{"put":"/api/v1/tasks/142","html":"http://s-app1.taskrabbit.com/tasks/my-first-task--16","get":"/api/v1/tasks/142","authenticated":"http://s-app1.taskrabbit.com/go/0cac931143e6c5d187b614558664b7b57989847b9d14658861928639edb4ce4f63687d762e68b12a8f51272dbfe47c5f0bc3","delete":"/api/v1/tasks/142"}}'
    http_version: '1.1'
