--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://localhost:3000/api/v1/tasks?
    body: task[name]=My%20First%20Task&task[named_price]=20&task[city_id]=4
    headers: 
      x-client-application: 
      - euqmQpzV04GmN1dJTY639PdI7eiSjCjI3lKTkPWn
      authorization: 
      - OAuth RhyRtRg1bRNyqmdozkY6JJJ3eGDpoRGTm9AXUudp
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 200
      message: OK
    headers: 
      etag: 
      - "\"0deecebf3ec5c0e5a8291a90f8c24ea7\""
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "2704"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2010-04-19)
      date: 
      - Fri, 04 Nov 2011 22:22:22 GMT
      content-length: 
      - "613"
      cache-control: 
      - private, max-age=0, must-revalidate
    body: "{\"name\":\"My First Task\",\"city\":{\"name\":\"New York City\",\"lng\":-74.005973,\"id\":4,\"links\":{\"get\":\"/api/v1/cities/4\"},\"lat\":40.714353},\"named_price\":20,\"complete_by_time\":1320519600,\"id\":22579,\"state_changed_at\":1320445341,\"cost_in_cents\":0,\"links\":{\"html\":\"http://local.taskrabbit.com/tasks/my-first-task--32\",\"get\":\"/api/v1/tasks/22579\",\"delete\":\"/api/v1/tasks/22579\",\"put\":\"/api/v1/tasks/22579\",\"authenticated\":\"http://local.taskrabbit.com/go/a0815946db902dd5d631695b6979fbeb5fc8fd1fc5e320eb9ccbf30da93b7f0c1d4f80181e9249490e7b2289d6b9ba48d29b\"},\"state_label\":\"posted\",\"assign_by_time\":1320505200,\"state\":\"opened\"}"
    http_version: "1.1"
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :put
    uri: http://localhost:3000/api/v1/tasks/22579?
    body: name=New%20Name&id=22579
    headers: 
      x-client-application: 
      - euqmQpzV04GmN1dJTY639PdI7eiSjCjI3lKTkPWn
      authorization: 
      - OAuth RhyRtRg1bRNyqmdozkY6JJJ3eGDpoRGTm9AXUudp
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 200
      message: OK
    headers: 
      etag: 
      - "\"39693202d06f3916756b10173dde36b4\""
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "1599"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2010-04-19)
      date: 
      - Fri, 04 Nov 2011 22:22:24 GMT
      content-length: 
      - "599"
      cache-control: 
      - private, max-age=0, must-revalidate
    body: "{\"name\":\"New Name\",\"city\":{\"name\":\"New York City\",\"lng\":-74.005973,\"id\":4,\"links\":{\"get\":\"/api/v1/cities/4\"},\"lat\":40.714353},\"named_price\":20,\"complete_by_time\":1320519600,\"id\":22579,\"state_changed_at\":1320445341,\"cost_in_cents\":0,\"links\":{\"html\":\"http://local.taskrabbit.com/tasks/new-name\",\"get\":\"/api/v1/tasks/22579\",\"delete\":\"/api/v1/tasks/22579\",\"put\":\"/api/v1/tasks/22579\",\"authenticated\":\"http://local.taskrabbit.com/go/913b4898d8fa6390189a3b58aad491f60b002257698b929d389376412ffbc5835ed513380652a182566671eb1f3583045298\"},\"state_label\":\"posted\",\"assign_by_time\":1320505200,\"state\":\"opened\"}"
    http_version: "1.1"
