--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: https://taskrabbitdev.com/api/v1/tasks?
    body: task[name]=My%20First%20Task&task[named_price]=20&task[city_id]=4
    headers: 
      x-client-application: 
      - <API_SECRET>
      authorization: 
      - OAuth <USER_WITH_CARD>
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 200
      message: OK
    headers: 
      etag: 
      - "\"3e2534e6d1fbd01d8fd94342e21bf9c3\""
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "4727"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2011-02-18)
      date: 
      - Sat, 17 Mar 2012 23:12:59 GMT
      content-length: 
      - "677"
      cache-control: 
      - private, max-age=0, must-revalidate
    body: "{\"name\":\"My First Task\",\"city\":{\"name\":\"New York City\",\"lng\":-74.005973,\"id\":4,\"links\":{\"get\":\"/api/v1/cities/4\"},\"lat\":40.714353},\"charge_price\":20,\"private_runner\":false,\"named_price\":20,\"complete_by_time\":1332093600,\"id\":22680,\"state_changed_at\":1332025978,\"cost_in_cents\":0,\"links\":{\"html\":\"http://local.taskrabbit.com/tasks/my-first-task--54\",\"get\":\"/api/v1/tasks/22680\",\"delete\":\"/api/v1/tasks/22680\",\"put\":\"/api/v1/tasks/22680\",\"authenticated\":\"http://local.taskrabbit.com/go/ee139b2757bbbf6c4eee502816d10ccc2e8ed72f608a44f3a3ba4d902e7d9f42f7411102b41821050c3f0a2be896dd812140\"},\"runners\":{\"items\":[]},\"state_label\":\"posted\",\"assign_by_time\":1332082800,\"state\":\"opened\"}"
    http_version: "1.1"
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :put
    uri: https://taskrabbitdev.com/api/v1/tasks/22680?
    body: name=New%20Name&id=22680
    headers: 
      x-client-application: 
      - <API_SECRET>
      authorization: 
      - OAuth <USER_WITH_CARD>
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 200
      message: OK
    headers: 
      etag: 
      - "\"8331cd17eb90f131337fc675d2d0fc5a\""
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "2003"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2011-02-18)
      date: 
      - Sat, 17 Mar 2012 23:13:02 GMT
      content-length: 
      - "666"
      cache-control: 
      - private, max-age=0, must-revalidate
    body: "{\"name\":\"New Name\",\"city\":{\"name\":\"New York City\",\"lng\":-74.005973,\"id\":4,\"links\":{\"get\":\"/api/v1/cities/4\"},\"lat\":40.714353},\"charge_price\":20,\"private_runner\":false,\"named_price\":20,\"complete_by_time\":1332093600,\"id\":22680,\"state_changed_at\":1332025978,\"cost_in_cents\":0,\"links\":{\"html\":\"http://local.taskrabbit.com/tasks/new-name--4\",\"get\":\"/api/v1/tasks/22680\",\"delete\":\"/api/v1/tasks/22680\",\"put\":\"/api/v1/tasks/22680\",\"authenticated\":\"http://local.taskrabbit.com/go/78196cf7905ad6c4b1fb0e4df943b284253a8880163ee3675cdf4b06a9b9de63f6b1cc198064ac121d7afce702d81be0fb03\"},\"runners\":{\"items\":[]},\"state_label\":\"posted\",\"assign_by_time\":1332082800,\"state\":\"opened\"}"
    http_version: "1.1"
