--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://localhost:3000/api/v1/tasks?
    body: task[name]=My%20First%20Task&task[named_price]=20&task[city_id]=4
    headers: 
      x-client-application: 
      - euqmQpzV04GmN1dJTY639PdI7eiSjCjI3lKTkPWn
      authorization: 
      - OAuth RhyRtRg1bRNyqmdozkY6JJJ3eGDpoRGTm9AXUudp
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 200
      message: OK
    headers: 
      etag: 
      - "\"f5947d1db0593762f7355ab9285f42d1\""
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "2901"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2010-04-19)
      date: 
      - Thu, 10 Nov 2011 22:05:36 GMT
      content-length: 
      - "613"
      cache-control: 
      - private, max-age=0, must-revalidate
    body: "{\"name\":\"My First Task\",\"city\":{\"name\":\"New York City\",\"lng\":-74.005973,\"id\":4,\"links\":{\"get\":\"/api/v1/cities/4\"},\"lat\":40.714353},\"named_price\":20,\"complete_by_time\":1321041600,\"id\":22592,\"state_changed_at\":1320962735,\"cost_in_cents\":0,\"links\":{\"html\":\"http://local.taskrabbit.com/tasks/my-first-task--45\",\"get\":\"/api/v1/tasks/22592\",\"delete\":\"/api/v1/tasks/22592\",\"put\":\"/api/v1/tasks/22592\",\"authenticated\":\"http://local.taskrabbit.com/go/680c02cbb64bef6bc398d58d4e6f28088ab03762ef0ac3b37b8a5f9bc64db9ba233b4b4a2e77f0c73bbd125a20bf9af6e505\"},\"state_label\":\"posted\",\"assign_by_time\":1321027200,\"state\":\"opened\"}"
    http_version: "1.1"
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :put
    uri: http://localhost:3000/api/v1/tasks/22592?
    body: name=New%20Name&id=22592
    headers: 
      x-client-application: 
      - euqmQpzV04GmN1dJTY639PdI7eiSjCjI3lKTkPWn
      authorization: 
      - OAuth RhyRtRg1bRNyqmdozkY6JJJ3eGDpoRGTm9AXUudp
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 200
      message: OK
    headers: 
      etag: 
      - "\"1d730a51387cc988388d967d2e66d675\""
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "1844"
      server: 
      - WEBrick/1.3.1 (Ruby/1.8.7/2010-04-19)
      date: 
      - Thu, 10 Nov 2011 22:05:39 GMT
      content-length: 
      - "602"
      cache-control: 
      - private, max-age=0, must-revalidate
    body: "{\"name\":\"New Name\",\"city\":{\"name\":\"New York City\",\"lng\":-74.005973,\"id\":4,\"links\":{\"get\":\"/api/v1/cities/4\"},\"lat\":40.714353},\"named_price\":20,\"complete_by_time\":1321041600,\"id\":22592,\"state_changed_at\":1320962735,\"cost_in_cents\":0,\"links\":{\"html\":\"http://local.taskrabbit.com/tasks/new-name--2\",\"get\":\"/api/v1/tasks/22592\",\"delete\":\"/api/v1/tasks/22592\",\"put\":\"/api/v1/tasks/22592\",\"authenticated\":\"http://local.taskrabbit.com/go/df1a28f14bf403b086d0825fb22e19566a7fd7a3acf48ea53b0b0932311523174421db519e93a4b793efc3d83017014f0f06\"},\"state_label\":\"posted\",\"assign_by_time\":1321027200,\"state\":\"opened\"}"
    http_version: "1.1"
